blog/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.blog_index, name="blog_index"),
    path('<int:pk>/', views.blog_detail, name="blog_detail"),
    path('<category>/', views.blog_category, name="blog_category")
]

hello_world/urls.py
from django.urls import path
from . import views
app_name = "hello_world"

urlpatterns = [
    path("", views.hello_world, name="hello_world")
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("projects/", include("projects.urls")),
    path('blog/', include("blog.urls"))
]

projects/urls.py
from django.urls import path
from . import views

app_name = "projects"

urlpatterns = [
    path("", views.project_index, name="project_index"),
    path("<int:pk>/", views.project_detail, name="project_detail"),
]

blog/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=20)


class Post(models.Model):
    title = models.CharField(max_length=255)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    categories = models.ManyToManyField('Category', related_name='posts')


class Comment(models.Model):
    author = models.CharField(max_length=60)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey('Post', on_delete=models.CASCADE)

hello_world/models.py
from django.db import models

# Create your models here.

projects/models.py
from django.db import models


# Create your models here.
class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    technology = models.CharField(max_length=20)
    image = models.FilePathField(path='/img')

blog/forms.py
from django import forms


class CommentForm(forms.Form):
    author = forms.CharField(
        max_length=60,
        widget=forms.TextInput(attrs={  # Load this "author" field as an HTML text input element in the templates
            "class": "form-control",
            "placeholder": "Your Name"
        })
    )
    body = forms.CharField(
        widget=forms.Textarea(attrs={
            "class": "form-control",
            "placeholder": "Leave a comment!"
        })
    )

blog/views.py
from django.shortcuts import render

# Create your views here.
from blog.forms import CommentForm
from blog.models import Post, Comment


def blog_index(request):
    posts = Post.objects.all().order_by('-created_on')
    context = {
        "posts": posts
    }
    return render(request, 'blog_index.html', context)


def blog_category(request, category):
    # Display all the posts under a specific category
    posts = Post.objects.filter(
        categories__name__contains=category
    ).order_by('-created_on')
    context = {
        "category": category,
        "posts": posts
    }
    return render(request, "blog_category.html", context)


def blog_detail(request, pk):
    # Show the detail of one blog -- post and comments
    post = Post.objects.get(pk=pk)
    form = CommentForm()
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = Comment(
                author=form.cleaned_data["author"],
                body=form.cleaned_data["body"],
                post=post
            )
            comment.save()

    comments = Comment.objects.filter(post=post)
    context = {
        "post": post,
        "comments": comments,
        "form": form
    }

    return render(request, "blog_detail.html", context)

hello_world/views.py
from django.shortcuts import render


# Create your views here.
def hello_world(request):
    return render(request, "hello_world.html", {})

projects/views.py
from django.shortcuts import render

from .models import Project


def project_index(request):
    projects = Project.objects.all()
    for project in projects:
        print(project.image)
    context = {
        'projects': projects
    }
    return render(request, 'project_index.html', context)


def project_detail(request, pk):
    # objects.get will get a object, objects.filter will get a queryset
    project = Project.objects.get(pk=pk)
    print(project.title)
    context = {
        'project': project
    }
    return render(request, 'project_detail.html', context)

blog/templates/blog_category.html
{% extends "base.html" %}
{% block page_content %}
    <div class="col-md-8 offset-md-2">
        <h1>{{ category | title }}</h1>
        <hr>
        {% for post in posts %}
        <h2><a href="{% url 'blog_detail' post.pk %}">{{ post.title }}</a></h2>
        <small>
            {{ post.created_on.date }} |&nbsp;
            Categories:&nbsp;
            {% for category in post.categories.all %}
                <a href="{% url 'blog_category' category.name %}">{{ category.name }}</a>&nbsp;
            {% endfor %}
        </small>
        <p>{{ post.body | slice:":400" }}...</p>
        {% endfor %}
    </div>
{% endblock page_content %}

blog/templates/blog_detail.html
{% extends "base.html" %}
{% block page_content %}
<div class="col-md-8 offset-md-2">
<h1>{{ post.title }}</h1>
<small>
    {{ post.created_on.date }} |&nbsp;
    Categories:&nbsp;
    {% for category in post.categories.all %}
        <a href="{% url 'blog_category' category.name %}">
            {{ category.name }}
        </a>&nbsp;
    {% endfor %}
</small>
<p>{{ post.body | linebreaks }}</p>
<h3>Leave a comment:</h3>
    <form action="/blog/{{ post.pk }}/" method="post">
        {% csrf_token %}
        <div class="form-group">
            {{ form.author }}
        </div>
        <div class="form-group">
            {{ form.body }}
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    <h3>Comments:</h3>
    {% for comment in comments %}
        <p>
            On {{ comment.created_on.date }}&nbsp;
            <b>{{ comment.author }}</b> wrote:
        </p>
        <p>{{ comment.body }}</p>
        <hr>
    {% endfor %}
</div>
{% endblock %}

blog/templates/blog_index.html
{% extends "base.html" %}
{% block page_content %}
    <div class="col-md-8 offset-md-2">
        <h1>Blog Index</h1>
        <hr>
        {% for post in posts %}
        <h2><a href="{% url 'blog_detail' post.pk %}">{{ post.title }}</a></h2>
        <small>
            {{ post.created_on.date }} |&nbsp;
            Categories:&nbsp;
            {% for category in post.categories.all %}
                <a href="{% url 'blog_category' category.name %}">{{ category.name }}</a>&nbsp;
            {% endfor %}
        </small>
        <p>{{ post.body | slice:":400" }}...</p>
        {% endfor %}
    </div>
{% endblock page_content %}

hello_world/templates/hello_world.html
{% extends 'base.html' %}
{% block page_content %}
    <h1>Hello world</h1>
{% endblock page_content %}

projects/templates/project_detail.html
{% extends 'base.html' %}
{% load static %}

{% block page_content %}
    <h1>{{ project.title }}</h1>
    <div class="row">
        <div class="col-md-8">
            <img src="{% static project.image %}" alt="Project Image" width="100%">
        </div>
        <div class="col-md-4">
            <h5>About the project:</h5>
            <p>{{ project.description }}</p>
            <br>
            <h5>Technology used:</h5>
            <p>{{ project.technology }}</p>
        </div>
    </div>
{% endblock page_content %}

projects/templates/project_index.html
{% extends "base.html" %}
{% load static %}
{% block page_content %}
<h1>Projects</h1>
<div class="row">
{% for project in projects %}
    <div class="col-md-4">
        <div class="card mb-2">
            <img class="card-img-top" src="{% static project.image %}" alt="My image">
            <div class="card-body">
                <h5 class="card-title">{{ project.title }}</h5>
                <p class="card-text">{{ project.description }}</p>
                <a href="{% url 'projects:project_detail' project.pk %}"
                   class="btn btn-primary">
                    Read More
                </a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

templates/base.html
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

<div class="container">
{% block page_content %}{% endblock page_content %}
</div>